#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#


exchange-rates:
    path: /api/exchange-rates/{when?}
    controller: App\Controller\ExchangeRatesController::getList
    requirements:
        when: "^([0-9]{4}-[0-9]{2}-[0-9]{2}$)*"

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

